services:
  keycloak:
    container_name: keycloak
    build: .
    restart: unless-stopped
    env_file:
      - .env.local
    ports:
      - 7080:8080
    networks:
      - web

  postgres:
    container_name: postgres
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - web

networks:
  web:
    external: true

volumes:
  postgres_data:
